//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

// pub use super::prelude::*;
pub mod prelude;
pub mod group;
pub mod permission;
pub mod permission_group;
pub mod user;
pub mod user_group;
